name: Taxon Request
description: Request a new taxon
title: "[Taxon]: "
labels: ["feature", "taxon"]
assignees:
  - ryanmwhitephd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this taxon request! Please refer to the [specification](https://measurand-taxonomy.readthedocs.io/en/latest/specification.html) for further details and guidance.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: process
    attributes:
      label: What is the process type? 
      description: A taxon’s first token represents the process type, taking either the value Measure or Source to identify an input-quanity or output-quantity measurement, respectively.
      multiple: true
      options:
        - Measure
        - Source
  - type: textarea
    id: measurand
    attributes:
      label: Measurand
      description: Provide a description of the measurand. Simply stated, the measurand identifies what we intend to measure [VIM3](https://jcgm.bipm.org/vim/en/2.3.html). A measurement will fit its purpose to the degree that the measurand specification unambiguously and accurately describes the intent. Provide as many details to describe the measurand as possible, including links to references. 
      placeholder: Tell us what you measure! For example, Microphone Sensivity. The measurand quantity is pressure sensitivity, ratio of dynamic output voltage to dynamic pressure, typically expressed as a logarithmic level quantity to 1 V/Pa. The primary calibration method is reciprocity that entail reciprocal measurements between a pair of microphones under controlled conditions per IEC 61094-2.
    validations:
      required: true
  - type: textarea
    id: quantitykind
    attributes:
      label: Kind of quantity
      description: Provide a kind of quantity for the measurand. The measure quantity's first token identifies the [kind of quantity](https://jcgm.bipm.org/vim/en/1.2.html) such as length, or in some cases a particular aspect of a kind of quantity such as thermodynamic temparture or ITS-90 temperature.
      placeholder: Voltage and Pressure
    validations:
      required: true
  - type: dropdown
    id: special
    attributes:
      label: Does the measurand require a special token?
      description: Special tokens with their own syntax identify common measurement scenarios. The Ratio quantity token precedes the quantity-kind token to identify a quotient of two like-kind quantities. The Coefficient quantity token precedes two successive and differing quantity-kind tokens to identify a quotient of two unlike quantity kinds. The Delta token follows the quantity(ies) to identify a further quantity that differs when measuring the quotient’s numerator and denominator. The Model token after a quantity introduces a standard instrument model.
      multiple: false
      options:
        - Ratio
        - Coefficient
        - Delta
        - Model
  - type: textarea
    id: parameters
    attributes:
      label: Parameters
      description: Specify the measurand's full state such that its definitional uncertainty is insignificant to other uncertainty components. The measurand state includes its kind of quantity, input quantities, influence quantities, and instrument operating conditions. Define these as parameters in this section. For further details refer to the [parameters specification](https://measurand-taxonomy.readthedocs.io/en/latest/specification.html#parameters).
      placeholder: Voltage Pressure Sensitivity
    validations:
      required: true
  - type: textarea
    id: name
    attributes:
      label: Taxon Name
      description: Propose a name following the [specification rules](https://measurand-taxonomy.readthedocs.io/en/latest/specification.html#measurand-name). This field is not required and can be left to the reviewer or expert to provide the unique taxon name.
      placeholder: Measure.Taxon.Coefficient.Voltage.Pressure
    validations:
      required: true
  - type: textarea
    id: reference_name
    attributes:
      label: External Reference Name
      description: Provide the name of external reference 
      placeholder: International Electrotechnical Vocabulary - 	Acoustics and electroacoustics 
    validations:
      required: false
  - type: textarea
    id: reference_value
    attributes:
      label: External Reference Value
      description: Provide a value (id, controlled terminology, etc.) of external reference 
      placeholder: IEV 801-25-60
    validations:
      required: false
  - type: textarea
    id: reference_url
    attributes:
      label: External Reference URL
      description: Provide a url 
      placeholder: https://www.electropedia.org 
    validations:
      required: false
  - type: textarea
    id: reference_url_title
    attributes:
      label: External Reference URL Title
      description: Provide the title of the reference
      placeholder: International Electrotechnical Vocabulary
    validations:
      required: false
  
