name: Taxon Request
description: Request a new taxon
title: "[Taxon]: "
labels: ["feature", "taxon"]
assignees:
  - ryanmwhitephd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this taxon request! Please refer to the [specification](https://measurand-taxonomy.readthedocs.io/en/latest/specification.html) for further details and guidance.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: process
    attributes:
      label: What is the process type? A taxon’s first token represents the process type, taking either the value Measure or Source to identify an input-quanity or output-quantity measurement, respectively.
      multiple: false
      options:
        - Measure
        - Source
  - type: textarea
    id: measurand
    attributes:
      label: Measurand
      description: Provide a description of the measurand. Simply stated, the measurand identifies what we intend to measure [VIM3](https://jcgm.bipm.org/vim/en/2.3.html). A measurement will fit its purpose to the degree that the measurand specification unambiguously and accurately describes the intent. Provide as many details to describe the measurand as possible, including links to references. 
      placeholder: Tell us what you measure! For example, Microphone Sensivity. The measurand quantity is pressure sensitivity, ratio of dynamic output voltage to dynamic pressure, typically expressed as a logarithmic level quantity to 1 V/Pa. The primary calibration method is reciprocity that entail reciprocal measurements between a pair of microphones under controlled conditions per IEC 61094-2.
    validations:
      required: false
  - type: textarea
    id: quantitykind
    attributes:
      label: Kind of quantity
      description: Provide a kind of quantity for the measurand. The measure quantity's first token identifies the [kind of quantity](https://jcgm.bipm.org/vim/en/1.2.html) such as length, or in some cases a particular aspect of a kind of quantity such as thermodynamic temparture or ITS-90 temperature.
      placeholder: Length
    validations:
      required: false
  - type: dropdown
    id: special
    attributes:
      label: Does the measurand require a special token?
      multiple: false
      options:
        - Ratio
        - Coefficient
        - Delta
        - Model
  - type: textarea
    id: name
    attributes:
      label: Taxon Name
      description: Propose a name?
      placeholder: Measure.Taxon
    validations:
      required: false
  
